In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("crop_production.csv")
df.head()

       season                 crop    area  production
0      Kharif             Arecanut  1254.0      2000.0
1      Kharif  Other Kharif pulses     2.0         1.0
2      Kharif                 Rice   102.0       321.0
3  Whole Year               Banana   176.0       641.0
4  Whole Year            Cashewnut   720.0       165.0

In [16]:
df

          season                 crop    area  production     Yield
0         Kharif             Arecanut  1254.0      2000.0  1.594896
1         Kharif  Other Kharif pulses     2.0         1.0  0.500000
2         Kharif                 Rice   102.0       321.0  3.147059
3     Whole Year               Banana   176.0       641.0  3.642045
4     Whole Year            Cashewnut   720.0       165.0  0.229167
...          ...                  ...     ...         ...       ...
9994      Kharif        Small millets  2020.0      1616.0  0.800000
9995        Rabi                Wheat   200.0       320.0  1.600000
9996  Whole Year         Dry chillies   320.0       480.0  1.500000
9997  Whole Year           Dry ginger   450.0      2475.0  5.500000
9998  Whole Year       Oilseeds total  3500.0      2887.0  0.824857

[9930 rows x 5 columns]

In [3]:
df['season'].unique()

array(['Kharif', 'Whole Year', 'Autumn', 'Rabi'], dtype=object)

In [4]:
df['crop'].unique()

array(['Arecanut', 'Other Kharif pulses', 'Rice', 'Banana', 'Cashewnut',
       'Coconut', 'Dry ginger', 'Sugarcane', 'Sweet potato', 'Tapioca',
       'Black pepper', 'Dry chillies', 'other oilseeds', 'Turmeric',
       'Maize', 'Moong(Green Gram)', 'Urad', 'Arhar/Tur', 'Groundnut',
       'Sunflower', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Horse-gram',
       'Jowar', 'Korra', 'Ragi', 'Tobacco', 'Gram', 'Wheat', 'Masoor',
       'Sesamum', 'Linseed', 'Safflower', 'Onion', 'other misc. pulses',
       'Samai', 'Small millets', 'Coriander', 'Potato',
       'Other  Rabi pulses', 'Soyabean', 'Beans & Mutter(Vegetable)',
       'Bhindi', 'Brinjal', 'Citrus Fruit', 'Cucumber', 'Grapes', 'Mango',
       'Orange', 'other fibres', 'Other Fresh Fruits', 'Other Vegetables',
       'Papaya', 'Pome Fruit', 'Tomato', 'Rapeseed &Mustard', 'Mesta',
       'Cowpea(Lobia)', 'Lemon', 'Pome Granet', 'Sapota', 'Cabbage',
       'Peas  (vegetable)', 'Niger seed', 'Bottle Gourd', 'Sannhamp',
       'Varagu', 'Garlic', 'Ginger', 'Oilseeds total', 'Pulses total'],
      dtype=object)

In [5]:
df.isnull().sum()

season         0
crop           0
area           0
production    69
dtype: int64

In [6]:
df.isnull().values.any()

True

In [7]:
df = df.dropna()
df

          season                 crop    area  production
0         Kharif             Arecanut  1254.0      2000.0
1         Kharif  Other Kharif pulses     2.0         1.0
2         Kharif                 Rice   102.0       321.0
3     Whole Year               Banana   176.0       641.0
4     Whole Year            Cashewnut   720.0       165.0
...          ...                  ...     ...         ...
9994      Kharif        Small millets  2020.0      1616.0
9995        Rabi                Wheat   200.0       320.0
9996  Whole Year         Dry chillies   320.0       480.0
9997  Whole Year           Dry ginger   450.0      2475.0
9998  Whole Year       Oilseeds total  3500.0      2887.0

[9930 rows x 4 columns]

In [8]:
df.isnull().sum()

season        0
crop          0
area          0
production    0
dtype: int64

In [9]:
df['Yield']=(df['production']/df['area'])
df.head()

       season                 crop    area  production     Yield
0      Kharif             Arecanut  1254.0      2000.0  1.594896
1      Kharif  Other Kharif pulses     2.0         1.0  0.500000
2      Kharif                 Rice   102.0       321.0  3.147059
3  Whole Year               Banana   176.0       641.0  3.642045
4  Whole Year            Cashewnut   720.0       165.0  0.229167

In [10]:
## Converting the (categorical) Using one hot encoding
df = pd.get_dummies(df,drop_first=True) #get_dummies helps u to create dummy variables wrt no of categories present
df.head()

,area,production,Yield,season_Kharif,season_Rabi,season_Whole Year,crop_Arhar/Tur,crop_Bajra,crop_Banana,crop_Beans & Mutter(Vegetable),...,crop_Tapioca,crop_Tobacco,crop_Tomato,crop_Turmeric,crop_Urad,crop_Varagu,crop_Wheat,crop_other fibres,crop_other misc. pulses,crop_other oilseeds
0,1254.0,2000.0,1.594896,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2.0,1.0,0.500000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,102.0,321.0,3.147059,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,176.0,641.0,3.642045,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,720.0,165.0,0.229167,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.columns

Index(['area', 'production', 'Yield', 'season_Kharif', 'season_Rabi',
       'season_Whole Year', 'crop_Arhar/Tur', 'crop_Bajra', 'crop_Banana',
       'crop_Beans & Mutter(Vegetable)', 'crop_Bhindi', 'crop_Black pepper',
       'crop_Bottle Gourd', 'crop_Brinjal', 'crop_Cabbage', 'crop_Cashewnut',
       'crop_Castor seed', 'crop_Citrus Fruit', 'crop_Coconut',
       'crop_Coriander', 'crop_Cotton(lint)', 'crop_Cowpea(Lobia)',
       'crop_Cucumber', 'crop_Dry chillies', 'crop_Dry ginger', 'crop_Garlic',
       'crop_Ginger', 'crop_Gram', 'crop_Grapes', 'crop_Groundnut',
       'crop_Horse-gram', 'crop_Jowar', 'crop_Korra', 'crop_Lemon',
       'crop_Linseed', 'crop_Maize', 'crop_Mango', 'crop_Masoor', 'crop_Mesta',
       'crop_Moong(Green Gram)', 'crop_Niger seed', 'crop_Oilseeds total',
       'crop_Onion', 'crop_Orange', 'crop_Other  Rabi pulses',
       'crop_Other Fresh Fruits', 'crop_Other Kharif pulses',
       'crop_Other Vegetables', 'crop_Papaya', 'crop_Peas  (vegetable)',
       'crop_Pome Fruit', 'crop_Pome Granet', 'crop_Potato',
       'crop_Pulses total', 'crop_Ragi', 'crop_Rapeseed &Mustard', 'crop_Rice',
       'crop_Safflower', 'crop_Samai', 'crop_Sapota', 'crop_Sesamum',
       'crop_Small millets', 'crop_Soyabean', 'crop_Sugarcane',
       'crop_Sunflower', 'crop_Sweet potato', 'crop_Tapioca', 'crop_Tobacco',
       'crop_Tomato', 'crop_Turmeric', 'crop_Urad', 'crop_Varagu',
       'crop_Wheat', 'crop_other fibres', 'crop_other misc. pulses',
       'crop_other oilseeds'],
      dtype='object')

In [12]:
df = df.rename({'season_Whole Year':'season_Whole_Year'}, axis=1)
df.head()

,area,production,Yield,season_Kharif,season_Rabi,season_Whole_Year,crop_Arhar/Tur,crop_Bajra,crop_Banana,crop_Beans & Mutter(Vegetable),...,crop_Tapioca,crop_Tobacco,crop_Tomato,crop_Turmeric,crop_Urad,crop_Varagu,crop_Wheat,crop_other fibres,crop_other misc. pulses,crop_other oilseeds
0,1254.0,2000.0,1.594896,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2.0,1.0,0.500000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,102.0,321.0,3.147059,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,176.0,641.0,3.642045,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,720.0,165.0,0.229167,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df = df.rename({'crop_Arhar/Tur':'crop_Arhar_Tur','crop_Beans & Mutter(Vegetable)':'crop_Beans_Mutter_Vegetable','crop_Black pepper':'crop_Black_pepper','crop_Bottle Gourd':'crop_Bottle_Gourd','crop_Castor seed':'crop_Castor_seed','crop_Citrus Fruit':'crop_Citrus_Fruit','crop_Cotton(lint)':'crop_Cotton_lint',
                'crop_Cowpea(Lobia)':'crop_Cowpea_Lobia','crop_Dry chillies':'crop_Dry_chillies','crop_Dry ginger':'crop_Dry_ginger','crop_Horse-gram':'crop_Horse_gram', 'crop_Moong(Green Gram)':'crop_Moong_Green_Gram','crop_Oilseeds total':'crop_Oilseeds_total','crop_Other  Rabi pulses':'crop_Other_Rabi_pulses',
                'crop_Other Fresh Fruits':'crop_Other_Fresh_Fruits','crop_Other Kharif pulses':'crop_Other_Kharif_pulses','crop_Other Vegetables':'crop_Other_Vegetables','crop_Peas  (vegetable)':'crop_Peas_vegetable','crop_Pome Fruit':'crop_Pome_Fruit','crop_Pome Granet':'crop_Pome_Granet','crop_Pulses total':'crop_Pulses_total',
                'crop_Rapeseed &Mustard':'crop_Rapeseed_Mustard','crop_Small millets':'crop_Small_millets','crop_Sweet potato':'crop_Sweet_potato', 'crop_other fibres':'crop_other_fibres','crop_other misc. pulses':'crop_other_misc_pulses', 'crop_other oilseeds':'crop_other_oilseeds', 'crop_Niger seed':'crop_Niger_seed'}, axis=1)
df.head()

,area,production,Yield,season_Kharif,season_Rabi,season_Whole_Year,crop_Arhar_Tur,crop_Bajra,crop_Banana,crop_Beans_Mutter_Vegetable,...,crop_Tapioca,crop_Tobacco,crop_Tomato,crop_Turmeric,crop_Urad,crop_Varagu,crop_Wheat,crop_other_fibres,crop_other_misc_pulses,crop_other_oilseeds
0,1254.0,2000.0,1.594896,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2.0,1.0,0.500000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,102.0,321.0,3.147059,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,176.0,641.0,3.642045,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,720.0,165.0,0.229167,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
cols = list(df.columns.values) #Make a list of all of the columns in the df
cols.pop(cols.index('Yield'))
df = df[cols+['Yield']] 
df.head()

,area,production,season_Kharif,season_Rabi,season_Whole_Year,crop_Arhar_Tur,crop_Bajra,crop_Banana,crop_Beans_Mutter_Vegetable,crop_Bhindi,...,crop_Tobacco,crop_Tomato,crop_Turmeric,crop_Urad,crop_Varagu,crop_Wheat,crop_other_fibres,crop_other_misc_pulses,crop_other_oilseeds,Yield
0,1254.0,2000.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1.594896
1,2.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.500000
2,102.0,321.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3.147059
3,176.0,641.0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3.642045
4,720.0,165.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.229167

In [15]:
df.columns

Index(['area', 'production', 'season_Kharif', 'season_Rabi',
       'season_Whole_Year', 'crop_Arhar_Tur', 'crop_Bajra', 'crop_Banana',
       'crop_Beans_Mutter_Vegetable', 'crop_Bhindi', 'crop_Black_pepper',
       'crop_Bottle_Gourd', 'crop_Brinjal', 'crop_Cabbage', 'crop_Cashewnut',
       'crop_Castor_seed', 'crop_Citrus_Fruit', 'crop_Coconut',
       'crop_Coriander', 'crop_Cotton_lint', 'crop_Cowpea_Lobia',
       'crop_Cucumber', 'crop_Dry_chillies', 'crop_Dry_ginger', 'crop_Garlic',
       'crop_Ginger', 'crop_Gram', 'crop_Grapes', 'crop_Groundnut',
       'crop_Horse_gram', 'crop_Jowar', 'crop_Korra', 'crop_Lemon',
       'crop_Linseed', 'crop_Maize', 'crop_Mango', 'crop_Masoor', 'crop_Mesta',
       'crop_Moong_Green_Gram', 'crop_Niger_seed', 'crop_Oilseeds_total',
       'crop_Onion', 'crop_Orange', 'crop_Other_Rabi_pulses',
       'crop_Other_Fresh_Fruits', 'crop_Other_Kharif_pulses',
       'crop_Other_Vegetables', 'crop_Papaya', 'crop_Peas_vegetable',
       'crop_Pome_Fruit', 'crop_Pome_Granet', 'crop_Potato',
       'crop_Pulses_total', 'crop_Ragi', 'crop_Rapeseed_Mustard', 'crop_Rice',
       'crop_Safflower', 'crop_Samai', 'crop_Sapota', 'crop_Sesamum',
       'crop_Small_millets', 'crop_Soyabean', 'crop_Sugarcane',
       'crop_Sunflower', 'crop_Sweet_potato', 'crop_Tapioca', 'crop_Tobacco',
       'crop_Tomato', 'crop_Turmeric', 'crop_Urad', 'crop_Varagu',
       'crop_Wheat', 'crop_other_fibres', 'crop_other_misc_pulses',
       'crop_other_oilseeds', 'Yield'],
      dtype='object')

In [16]:
X = df.drop(columns=['Yield'])
y = df['Yield']

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [18]:
from sklearn.ensemble import RandomForestRegressor
rf_random = RandomForestRegressor()

In [19]:
#Hyperparameters
n_estimators = [int(x) for x in np.linspace(start=100, stop=1200, num=12)] #selecting diff decision trees
print(n_estimators)

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]

In [20]:
from sklearn.model_selection import RandomizedSearchCV

In [21]:
#Randomized Search CV, helps to find best parameters

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

In [22]:
# Create the random grid
# taking in the form of key value pair
random_grid = {'n_estimators':n_estimators,
               'max_features':max_features,
               'max_depth':max_depth,
               'min_samples_split':min_samples_split,
               'min_samples_leaf':min_samples_leaf}
print(random_grid) #randomizedCv will select the best parameters from this

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}

In [23]:
# Use the random grid to search for best hyperparams
#First create the best model to tune
rf = RandomForestRegressor()

In [24]:
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, scoring='neg_mean_squared_error', n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

In [25]:
rf_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.6s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   4.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   4.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   4.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   4.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   4.2s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=100, n_estimators=300; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=100, n_estimators=300; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=100, n_estimators=300; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=100, n_estimators=300; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=100, n_estimators=300; total time=   6.5s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=5, n_estimators=400; total time=   9.0s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=5, n_estimators=400; total time=   8.9s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=5, n_estimators=400; total time=   8.9s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=5, n_estimators=400; total time=   9.0s
[CV] END max_depth=15, max_features=auto, min_samples_leaf=5, min_samples_split=5, n_estimators=400; total time=   9.0s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=10, min_samples_split=5, n_estimators=700; total time=  19.2s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=10, min_samples_split=5, n_estimators=700; total time=  19.1s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=10, min_samples_split=5, n_estimators=700; total time=  19.2s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=10, min_samples_split=5, n_estimators=700; total time=  19.3s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=10, min_samples_split=5, n_estimators=700; total time=  19.4s
[CV] END max_depth=25, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=1000; total time=   6.9s
[CV] END max_depth=25, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=1000; total time=   6.9s
[CV] END max_depth=25, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=1000; total time=   6.8s
[CV] END max_depth=25, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=1000; total time=   6.8s
[CV] END max_depth=25, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=1000; total time=   7.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=10, min_samples_split=15, n_estimators=1100; total time=   2.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=10, min_samples_split=15, n_estimators=1100; total time=   2.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=10, min_samples_split=15, n_estimators=1100; total time=   2.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=10, min_samples_split=15, n_estimators=1100; total time=   2.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=10, min_samples_split=15, n_estimators=1100; total time=   2.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=1, min_samples_split=15, n_estimators=300; total time=   1.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=1, min_samples_split=15, n_estimators=300; total time=   1.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=1, min_samples_split=15, n_estimators=300; total time=   1.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=1, min_samples_split=15, n_estimators=300; total time=   1.1s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=1, min_samples_split=15, n_estimators=300; total time=   1.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=700; total time=   1.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=700; total time=   1.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=700; total time=   1.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=700; total time=   1.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=700; total time=   1.3s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=15, n_estimators=700; total time=  19.5s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=15, n_estimators=700; total time=  19.6s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=15, n_estimators=700; total time=  19.6s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=15, n_estimators=700; total time=  19.6s
[CV] END max_depth=20, max_features=auto, min_samples_leaf=1, min_samples_split=15, n_estimators=700; total time=  19.7s

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [26]:
#our model is now ready now we do the predictions
predictions = rf_random.predict(X_test)

In [27]:
predictions

array([1.81871396, 4.49289394, 6.59166647, ..., 7.32935932, 4.0843296 ,
       0.88183527])

In [28]:
from sklearn.metrics import r2_score
score = r2_score(y_test,predictions)
score

0.9676337372441084

In [29]:
from sklearn import metrics

In [30]:
import pickle

In [31]:
#Open a file for storing the data
file = open("random_forest_regression_model.pkl", 'wb')

#dump information to that file
pickle.dump(rf_random, file)